-- Migration: tables needed by features ported from the Python app (morning_brief)
-- Run in Supabase SQL editor. Safe to run repeatedly.

-- Meetings already summarized+delivered (the 15-min summary job skips these)
CREATE TABLE IF NOT EXISTS seen_meetings (
    event_id TEXT PRIMARY KEY,
    owner_upn TEXT,
    subject TEXT,
    summarized_at TIMESTAMPTZ DEFAULT NOW()
);

-- Per-user key/value settings
CREATE TABLE IF NOT EXISTS settings (
    owner_upn TEXT NOT NULL,
    key TEXT NOT NULL,
    value TEXT,
    PRIMARY KEY (owner_upn, key)
);

-- Saved places (work / home / customer), one primary per (owner, category)
CREATE TABLE IF NOT EXISTS places (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_upn TEXT NOT NULL,
    category TEXT NOT NULL,
    label TEXT NOT NULL,
    location TEXT,
    lat TEXT,
    lng TEXT,
    is_primary BOOLEAN DEFAULT FALSE,
    visit_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Track last reminder time per task (used by the hourly reminder job)
ALTER TABLE tasks ADD COLUMN IF NOT EXISTS reminded_at TIMESTAMPTZ;

-- Calendar events already pushed to LINE as "นัดใหม่"
CREATE TABLE IF NOT EXISTS calendar_notified (
    owner_upn TEXT NOT NULL,
    event_id TEXT NOT NULL,
    subject TEXT,
    notified_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (owner_upn, event_id)
);

-- RLS on (no policies): service key only, same as existing tables
ALTER TABLE seen_meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE places ENABLE ROW LEVEL SECURITY;
ALTER TABLE calendar_notified ENABLE ROW LEVEL SECURITY;
