-- Agent activity trace — powers the /monitor "AI at work" view.
-- One row per pipeline STAGE (no message content is stored — stages only).
-- Run in Supabase SQL editor. Safe to run repeatedly.

CREATE TABLE IF NOT EXISTS agent_traces (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trace_id UUID NOT NULL,          -- one id per incoming request
    upn TEXT,                        -- who triggered it
    channel TEXT,                    -- 'line' | 'web'
    step TEXT NOT NULL,              -- receive | parse | fetch | compose | reply | error
    label TEXT,                      -- short, non-PII (e.g. "intent=availability")
    status TEXT NOT NULL DEFAULT 'done', -- start | done | error
    seq INT DEFAULT 0,               -- order within a trace
    ms INT,                          -- ms offset from request start (for replay)
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_agent_traces_created ON agent_traces (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_agent_traces_trace ON agent_traces (trace_id);

-- RLS on, no policies: only the service_role key (server) can read/write.
ALTER TABLE agent_traces ENABLE ROW LEVEL SECURITY;
