-- Schema for Supabase PostgreSQL (ai-assistant-online)

CREATE TABLE IF NOT EXISTS feeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_upn TEXT NOT NULL,
    kind TEXT NOT NULL,           -- 'rss' | 'youtube' | 'facebook'
    ref TEXT NOT NULL,
    label TEXT,
    last_seen TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(owner_upn, kind, ref)
);

CREATE TABLE IF NOT EXISTS consents (
    owner_upn TEXT NOT NULL,
    capability TEXT NOT NULL,     -- read_tracking | src_rss | src_youtube | src_facebook
    granted BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (owner_upn, capability)
);

CREATE TABLE IF NOT EXISTS read_links (
    code TEXT PRIMARY KEY,
    owner_upn TEXT NOT NULL,
    url TEXT NOT NULL,
    source TEXT,
    title TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_upn TEXT NOT NULL,
    title TEXT NOT NULL,
    detail TEXT,
    responsible TEXT,
    responsible_upn TEXT,
    due TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'pending',
    source TEXT,
    dedup_key TEXT UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- LINE account link (M365 UPN <-> LINE userId)
CREATE TABLE IF NOT EXISTS line_links (
    upn TEXT PRIMARY KEY,
    line_user_id TEXT NOT NULL,
    display_name TEXT,
    linked_at TIMESTAMPTZ DEFAULT NOW()
);

-- Reading behaviour (only written when read_tracking consent granted)
CREATE TABLE IF NOT EXISTS reads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_upn TEXT NOT NULL,
    url TEXT,
    source TEXT,
    title TEXT,
    read_at TIMESTAMPTZ DEFAULT NOW()
);

-- OAuth refresh tokens for connected sources (e.g. Google/YouTube)
CREATE TABLE IF NOT EXISTS oauth_tokens (
    owner_upn TEXT NOT NULL,
    provider TEXT NOT NULL,
    refresh_token TEXT,
    scope TEXT,
    account_email TEXT,
    account_name TEXT,
    account_channel TEXT,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (owner_upn, provider)
);

-- Persistent chat logs for LLM Fine-Tuning dataset
CREATE TABLE IF NOT EXISTS chat_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id TEXT NOT NULL,
    user_upn TEXT,
    channel TEXT NOT NULL DEFAULT 'line',
    role TEXT NOT NULL,
    content TEXT NOT NULL,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

