-- Schema for Supabase PostgreSQL (ai-assistant-online)

CREATE TABLE IF NOT EXISTS feeds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_upn TEXT NOT NULL,
    kind TEXT NOT NULL,           -- 'rss' | 'youtube' | 'facebook'
    ref TEXT NOT NULL,
    label TEXT,
    last_seen TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(owner_upn, kind, ref)
);

CREATE TABLE IF NOT EXISTS consents (
    owner_upn TEXT NOT NULL,
    capability TEXT NOT NULL,     -- read_tracking | src_rss | src_youtube | src_facebook
    granted BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    PRIMARY KEY (owner_upn, capability)
);

CREATE TABLE IF NOT EXISTS read_links (
    code TEXT PRIMARY KEY,
    owner_upn TEXT NOT NULL,
    url TEXT NOT NULL,
    source TEXT,
    title TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_upn TEXT NOT NULL,
    title TEXT NOT NULL,
    detail TEXT,
    due TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'pending',
    created_at TIMESTAMPTZ DEFAULT NOW()
);
